source_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
org_id: xxxxxxxxxxxxxxxx
api_key: xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
push_url: pushdev.cloud.coveo.com

search_api_key: xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
search_url: https://platformdev.cloud.coveo.com/rest/search